

#eureka:
##  instance:
##    hostname: localhost
#  client:
##      registerWithEureka: false
##      fetchRegistry: false
##    register-with-eurika: false
#    fetch-registry: false
#    register-with-eureka: false
#
#server:
#  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

server:
  port: 8761